#!/usr/bin/env bash

set -e

update_json() {
	local board=$1
	local boardid=$2
	local year=$3
	local url
	mkdir -p "leaderboards/$board"
	url="https://adventofcode.com/$year/leaderboard/private/view/$boardid.json"
	curl -s -b session="$(< cookie)" "$url" | jq -S '.' > "leaderboards/$board/$year.json.tmp"
	if [[ ! -s leaderboards/$board/$year.json.tmp ]]; then
		echo "Could not get new data from adventofcode.com, session cookie expired?" >&2
		rm "leaderboards/$board/$year.json.tmp"
		exit 1
	fi

	# Compare to current leaderboard and signal in return status if year has to be built
	if cmp -s "leaderboards/$board/$year.json" "leaderboards/$board/$year.json.tmp"; then
		rm -f "leaderboards/$board/$year.json.tmp"
		return 1
	else
		mv "leaderboards/$board/$year.json.tmp" "leaderboards/$board/$year.json"
		return 0
	fi
}

gen_histogram() {
	local board=$1
	local year=$2
	jq -r '
		if .event == "2018" then
			del(.members[].completion_day_level["6"])
		elif .event == "2020" then
			del(.members[].completion_day_level["1"])
		else
			.
		end
		| .members[].completion_day_level[][].get_star_ts
	' "leaderboards/$board/$year.json" \
		| sed 's/^/@/' \
		| date -f - '+%H' \
		| sort \
		| uniq -c \
		| awk '{ print $2 "\t" $1 }' > "docs/$board/$year/histodata.tsv"

	gnuplot -c gnuplot/histo.gpi "docs/$board/$year/histodata.tsv" > "docs/$board/$year/histo.svg"
}

gen_submission_stamps() {
	local board=$1
	local year=$2

	# shellcheck disable=SC2016
	# This gets a list of day - star - timestamp:
	jq -r '
		[
			.members[].completion_day_level |
			paths(scalars) as $p |
			getpath($p) as $v |
			($p | map(strings) + [$v]) |
			[(.[0,1] | tonumber), .[3]]
		] | sort | .[] | @tsv
	' "leaderboards/$board/$year.json" > "docs/$board/$year/submission_times.tsv"
}

gen_submission_stamps_day() {
	local board=$1
	local year=$2
	local day=$3
	local basedate

	printf -v basedate '%d-12-%02dT00:00:00-0500' "$year" "$day"

	awk -v day="$day" -v midnight="$(date '+%s' -d "$basedate")" '
		BEGIN { secsinday = 24 * 3600 }
		$1 == day {
			if ($3 - midnight <= secsinday ) {
			if ($2 == 1)
				first[++i] = $3 - midnight
			else
				second[++j] = $3 - midnight
			}
		}
		END {
			for (i = 1; i <= length(first); ++i)
			print first[i] "\t" second[i]
		}
	' "docs/$board/$year/submission_times.tsv"
}

rank_day_star() {
	local board$1
	local year=$2
	local day=$3
	local star=$4
	local basedate basedate_unix
	local name
	local tstamp1 tstamp2
	local n
	n=$(jq '.members | length' "leaderboards/$board/$year.json")

	printf -v basedate '%d-12-%02dT00:00:00-0500' "$year" "$day"
	basedate_unix=$(date '+%s' -d "$basedate")

	# shellcheck disable=SC2016,SC1004
	jq -r --arg day "$day" --arg star "$star" '
		[.members[]] |
		if $star == "1" then
			map( {name, id, tstamp: .completion_day_level[$day][$star].get_star_ts} )
		else
			map( {
				name,
				id,
				tstamp: .completion_day_level[$day][$star].get_star_ts,
				tstamp1: .completion_day_level[$day]["1"].get_star_ts
			} )
		end |
		sort_by(.tstamp)[] |
		select(.tstamp != null) |
		[.name // ("User #" + .id), .tstamp, .tstamp1 // ""] |
		@tsv
	' "leaderboards/$board/$year.json" \
		| while IFS=$'\t' read -r name tstamp1 tstamp2; do
			printf '%s\t%s\t%s\n' \
				"$name" \
				"$((tstamp1 - basedate_unix))" \
				"${tstamp2:+$((tstamp1 - tstamp2))}"
		done \
		| awk -F '\t' -v n="$n" '
		{
			name[NR] = $1
			time[NR] = $2
			if ($3 != "")
				time1[NR] = $3
		}
		END {
			for (i = 1; i <= NR; ++i) {
				# Rank, name and time for star since midnight
				printf "%2d\t%s\t%3d:%02d:%02d", \
					i, name[i], int(time[i]/3600), int((time[i]%3600)/60), int((time[i]%60))

				# If second star, print time since first star
				if (length(time1)) {
					printf "\t%3d:%02d:%02d", \
						int(time1[i]/3600), int((time1[i]%3600)/60), int((time1[i]%60))
				}

				# Points for local ranking
				printf "\t%d\n", n - i + 1
			}
		}
	'
}

print_header() {
	local title=$1
	local re1='Ranking ([[:graph:]]+) (20..) day ([[:digit:]]+), star ([[:digit:]]+)'
	local re2='Submission times graph, [[:graph:]]+ (20..) day ([[:digit:]]+)'
	if [[ $title =~ $re1 ]]; then
		local board=${BASH_REMATCH[1]}
		local year=${BASH_REMATCH[2]}
		local day
		printf -v day '%02d' "${BASH_REMATCH[3]}"
		local star=$((BASH_REMATCH[4] == 1 ? 2 : 1))
		local starlink
		printf -v starlink '<a href="day%sstar%d.html">Ranking for star %d</a>' \
			"$day" "$star" "$star"
		local graphlink

		if [[ -s docs/$board/$year/day${day}subm.html ]]; then
			printf -v graphlink ' <a href="day%ssubm.html">Submission graph for day %s</a>' \
				"$day" "${day#0}"
		else
			graphlink=''
		fi
		local linkbar="<p>$starlink$graphlink"

		if ((year == 2018 && 10#$day == 6)) || ((year == 2020 && 10#$day == 1)); then
			local note='<p>This day does not count for the total score.</p>'
		fi
	elif [[ $title =~ $re2 ]]; then
		local year=${BASH_REMATCH[1]}
		local day=${BASH_REMATCH[2]}
		local starlink1
		printf -v starlink1 '<a href="day%02dstar1.html">Ranking for star 1</a>' "$day"
		local starlink2
		printf -v starlink2 '<a href="day%02dstar2.html">Ranking for star 2</a>' "$day"
		local linkbar="<p>$starlink1 $starlink2"
	fi

	if [[ -n $linkbar ]]; then
		local problemlink
		printf -v problemlink '<a href="https://adventofcode.com/%d/day/%d">' "$year" "${day#0}"
		problemlink+='Problem definition</a>'
		linkbar+=" $problemlink</p>"
	fi

	cat <<- EOF
		<!doctype html>
		<html>
		<head>
		<meta charset=utf-8>
		<link rel="stylesheet" href="/aoc-stats/style.css">
		<link rel="shortcut icon" href="/aoc-stats/favicon.png" type="image/x-icon">
		<title>$title</title>
		</head>
		<body>
		<h1>$title</h1>
		$linkbar
		$note
	EOF
}

tablify() {
	local fname=$1
	shift
	local col_headings=("$@")
	local link=${fname##*/}

	awk -v link="$link" -v date="$(date)" '
		BEGIN {
			FS = "\t"
			print "<div><table>"
			print "<tr>"
			print "<th>Rank</th>"
			print "<th>Name</th>"

			# Loop over all but last argument
			for (i = 1; i < ARGC-1; ++i) {
				print "<th>" ARGV[i]  "</th>"
				delete ARGV[i]
			}
			print "</tr>"
		}
		{
			print "<tr>"
			for (i = 1; i <= NF; ++i)
				print "<td>" $i "</td>"
			print "</tr>"
		}
		END {
			print "</table></div>"
			print "<p><a href=\"index.html\">Return to index</a></p>"
			print "<p class=\"tstamp\">Last updated " date "</p>"
		}
	' "${col_headings[@]}" "$fname"
}

gen_tsv_files() {
	local board=$1
	local year=$2
	local day
	local star

	for day in {01..25}; do
		for star in 1 2; do
			rank_day_star "$board" "$year" "${day#0}" "$star" \
				> "docs/$board/$year/day${day}star$star.tsv"
		done
		gen_submission_stamps_day "$board" "$year" "${day#0}" \
			> "docs/$board/$year/day${day}subm.tsv"

		# Throw away empty file
		[[ -s docs/$board/$year/day${day}subm.tsv ]] \
			|| rm -f "docs/$board/$year/day${day}subm.tsv"
	done
}

gen_subm_graphs() {
	local board=$1
	local year=$2
	local day

	for day in {01..25}; do
		[[ -e docs/$board/$year/day${day}subm.tsv ]] || continue
		gnuplot -c gnuplot/submtime.gpi "docs/$board/$year/day${day}subm.tsv" \
			> "docs/$board/$year/day${day}subm.svg"
	done
}

gen_local_score() {
	local board=$1
	local year=$2
	jq -r '
		[.members[]
		| [.name // "User #" + .id, .local_score, .global_score, .stars]
		| select(.[4] > 0)]
		| sort_by(-.[1])
		| to_entries[]
		| [.key+1, .value[]]
		| @tsv
	' "leaderboards/$board/$year.json" > "docs/$board/$year/local_score.tsv"
}

gen_html_files() {
	local board=$1
	local year=$2

	local star_tab_headers=(
		'Time to solve [h:m:s]'
		'Local score'
	)

	local star2_tab_headers=(
		'Time to solve [h:m:s]'
		'Time since star 1 [h:m:s]'
		'Local score'
	)

	local re='day([0-9]+)star([0-9])\.tsv$'
	local fname day star

	for fname in "docs/$board/$year"/day*star*.tsv; do
		[[ $fname =~ $re ]]
		day=${BASH_REMATCH[1]}
		star=${BASH_REMATCH[2]}

		{
			print_header "Ranking $board $year day ${day#0}, star $star"
			if ((star == 1)); then
				tablify "$fname" "${star_tab_headers[@]}"
			else
				tablify "$fname" "${star2_tab_headers[@]}"
			fi
		} | tidy "${tidyopts[@]}" > "${fname%.tsv}.html"
	done

	for day in {01..25}; do
		fname=day${day}subm.svg
		[[ -s docs/$board/$year/$fname ]] || continue

		{
			print_header "Submission times graph, $board $year day ${day#0}"
			cat <<- EOF
				<img src="$fname" alt="$year submission times day $day">
				<p><a href="index.html">Return to index</a></p>
				<p class="tstamp">Last updated $(date)</p>
			EOF
		} | tidy "${tidyopts[@]}" > "docs/$board/$year/${fname%svg}html"
	done

	{
		print_header "$board $year local score"
		echo "<p>For each star, winner gets one point per participant, runner-up one less etc.</p>"
		if ((year == 2018)); then
			echo "<p>Day number 6 is ignored for the total shown here as there was a bug in the puzzle.</p>"
		fi
		if ((year == 2020)); then
			echo "<p>Day number 1 is ignored for the total shown here as there was an outage at unlock.</p>"
		fi
		tablify "docs/$board/$year/local_score.tsv" 'Points' 'Global' 'Stars'
	} | tidy "${tidyopts[@]}" > "docs/$board/$year/local_score.html"

	{
		print_header "$board $year histogram of submission times"
		if ((year == 2018)); then
			echo "<p>Submissions from day 6 are not shown, there was a bug in the puzzle.</p>"
		fi
		if ((year == 2020)); then
			echo "<p>Submissions from day 1 are not shown, there was an outage at unlock.</p>"
		fi
		cat <<- EOF
			<img src="histo.svg" alt="$year histogram of submission times">
			<p><a href="index.html">Return to index</a></p>
			<p class="tstamp">Last updated $(date)</p>
		EOF
	} | tidy "${tidyopts[@]}" > "docs/$board/$year/histo.html"

	{
		print_header "$board $year running total over time"
		if ((year == 2018)); then
			echo "<p>Submissions from day 6 are ignored as there was a bug in the puzzle.</p>"
		fi
		if ((year == 2020)); then
			echo "<p>Submissions from day 1 are ignored as there was an outage at unlock.</p>"
		fi
		cat <<- EOF
			<img src="time_vs_points.svg" alt="$year running total over time">
			<p><a href="index.html">Return to index</a></p>
			<p class="tstamp">Last updated $(date)</p>
		EOF
	} | tidy "${tidyopts[@]}" > "docs/$board/$year/over_time.html"
}

gen_index() {
	local board=$1
	local year=$2
	local histo_link over_time_link
	{
		print_header "Advent of Code $year, $board Stats"
		if [[ -s docs/$board/$year/histo.svg ]]; then
			histo_link='<li><p><a href="histo.html">Histogram of submission times</a></p></li>'
		else
			histo_link=''
		fi

		if [[ -s docs/$board/$year/time_vs_points.svg ]]; then
			over_time_link='<li><p><a href="over_time.html">Graph of running totals</a></p></li>'
		else
			over_time_link=''
		fi

		cat <<- EOF
			<h2>Overall rankings and statistics</h2>
			<ul>
			<li><p><a href="local_score.html">Local score</a></p></li>
			$histo_link
			$over_time_link
			</ul>
			<h2>Graphs and rankings per day and star</h2>
			<div>
			<table class="listleft">
		EOF

		local re='day([[:digit:]]+)star([12])\.html$'
		local fname remark1 remark2
		for fname in "docs/$board/$year"/day*star*.html; do
			[[ $fname =~ $re ]]
			local day=${BASH_REMATCH[1]}
			local star=${BASH_REMATCH[2]}

			local marker
			if [[ ! -s ${fname%.html}.tsv ]]; then
				marker='<sup>*'
				remark1='<p><sup>*</sup>Day with no results yet</p>'
				daylink="Day ${day#0}"
			elif [[ ! -f docs/$board/$year/day${day}subm.svg ]]; then
				marker='<sup>+'
				remark2='<p><sup>+</sup>Day without submissions in the first 24 hours</p>'
				daylink="Day ${day#0}"
			else
				marker='<sup>'
				daylink="<a href=\"day${day}subm.html\">Day ${day#0}</a>"
			fi

			# These days had bugs and don't count
			if ((year == 2018 && 10#$day == 6)) || ((year == 2020 && 10#$day == 1)); then
				marker+='o'
				local remark3='<p><sup>o</sup>Day does not count for total score</p>'
			fi
			marker+='</sup>'
			[[ $marker == '<sup></sup>' ]] && marker=''

			if ((10#$day == 14 && star == 1)); then
				echo '</table><table class="listright">'
			fi

			if ((star == 1)); then
				cat <<- EOF
					<tr>
					<td class="day">$marker$daylink</td>
					<td><a href="${fname##*/}">Star 1</a></td>
				EOF
			elif ((star == 2)); then
				cat <<- EOF
					<td><a href="${fname##*/}">Star 2</a></td>
					</tr>
				EOF
			fi
		done

		cat <<- EOF
			</table>
			</div>
			<div class="vertsep"></div>
			$remark1
			$remark2
			$remark3
			<p><a href="../../index.html">Return to index</a></p>
			<p>
				Suggest more stats in the <a href="https://github.com/bewuethr/aoc-stats/issues">issue tracker</a>
			</p>
			<p class="tstamp">Last updated $(date)</p>
		EOF
	} | tidy "${tidyopts[@]}" > "docs/$board/$year/index.html"
}

gen_main_index() {
	{
		print_header "Advent of Code Extended Stats"

		local boardpath board yearpath year

		for boardpath in docs/*; do
			[[ ! -d $boardpath ]] && continue
			board=${boardpath#*/}
			echo "<h2>$board</h2>"
			echo '<table>'

			for yearpath in "$boardpath"/*; do
				year=${yearpath##*/}
				printf '<tr><td class="year"><a href="%s/%s/index.html">Rankings for %s</a></td></tr>' \
					"$board" "$year" "$year"
			done
			echo '</table>'
		done

		cat <<- EOF
			<p>
				Suggest more stats in the <a href="https://github.com/bewuethr/aoc-stats/issues">issue tracker</a>
			</p>
			<p class="tstamp">Last updated $(date)</p>
		EOF
	} | tidy "${tidyopts[@]}" > docs/index.html
}

push_changes() {
	local status
	status=$(git status --porcelain docs)
	if [[ -n $status ]]; then
		git add docs leaderboards
		git commit -m "Update rankings"
		git push --quiet

	else
		echo "No changes, not pushing anything" >&2
	fi
}

shopt -s globstar

while getopts ":dfpv" opt; do
	case $opt in
		d) debug='yes' ;;
		f) fetch='yes' ;;
		p) push='yes' ;;
		v) verbose='yes' ;;
		\?) echo "Invalid option: -$OPTARG" >&2 && exit 1 ;;
	esac
done

tidyopts=(-iq --tidy-mark no --wrap 120)

[[ -n $verbose ]] && date
[[ -n $fetch ]] && git pull --quiet

while read -r board boardid yearstr; do
	IFS=, read -ra years <<< "$yearstr"
	for year in "${years[@]}"; do
		if [[ -n $fetch ]]; then
			if ! update_json "$board" "$boardid" "$year"; then
				[[ $verbose ]] && echo "$board $year has not changed, skipping" >&2
				continue
			fi
		fi
		[[ $verbose ]] && echo "Building $board $year" >&2
		mkdir -p "docs/$board/$year"
		gen_histogram "$board" "$year"
		./buildlgraph "$board" "$year"
		gen_submission_stamps "$board" "$year"
		gen_tsv_files "$board" "$year"
		gen_subm_graphs "$board" "$year"
		gen_local_score "$board" "$year"
		gen_html_files "$board" "$year"
		gen_index "$board" "$year"
		gen_main_flag='yes'
	done
done < <(sed '1d' boardids)

[[ -n $gen_main_flag ]] && gen_main_index

[[ -n $debug ]] || rm -rf ./**/*.tsv

[[ -n $push ]] && push_changes
