#!/bin/bash

rank_day_star () {
    local day=$1
    local star=$2
    local basedate
    local name
    local time

    printf -v basedate '2016-12-%02dT00:00:00-05:00' "$day"

    jq -r --arg day "$day" --arg star "$star" '
        [.members[]] |
        map( {name, tstamp: .completion_day_level[$day][$star].get_star_ts} ) |
        sort_by(.tstamp)[] |
        select(.name != null) |
        select(.tstamp != null) |
        [.name, .tstamp] |
        @tsv
    ' < leaderboard.json |
    while IFS=$'\t' read name time; do
        printf '%s\t%s\n' "$name" "$(( $(date +'%s' -d "$time") - $(date +'%s' -d "$basedate") ))"
    done |
    awk -F "\t" -v day="$day" -v star="$star" '
        { printf "%2d\t%s\t%3d:%02d\n", NR, $1, int($2/3600), int(($2%3600)/60) }
    '
}

print_header () {
    local title=$1

    cat <<EOF
        <!doctype html>
        <html>
        <head>
        <meta charset=utf-8>
        <title>$title</title>
        </head>
        <body>
        <h1>$title</h1>
EOF
}

tablify () {
    local fname=$1
    local col3_heading=$2
    awk -v col3_heading="$col3_heading" -v fname="$fname" '
        BEGIN {
            FS = "\t"
            print "<div><table>"
            print "<tr>"
            print "<th>Rank</th>"
            print "<th>Name</th>"
            print "<th>" col3_heading "</th>"
            print "</tr>"
        }
        {
            print "<tr>"
            for (i = 1; i <= NF; ++i)
                print "<td>" $i "</td>"
            print "</tr>"
        }
        END {
            print "</table></div>"
            print "<p>Raw text file: <a href=\"" fname "\">" fname "</a></p>"
            print "<p><a href=\"..\">Return to index</a></p>"
        }
    '
}

gen_txt_files () {
    local day
    local star

    for day in {01..25}; do
        for star in 1 2; do
            rank_day_star "${day#0}" "$star" > "day${day}star$star".txt
        done
    done
}

gen_local_score () {
    awk '
        BEGIN {
            FS = "\t"
            PROCINFO["sorted_in"] = "@val_num_desc"
        }
        { rank[$2][FILENAME] = $1 }
        END {
            n = length(rank)
            for (i in rank)
                for (j in rank[i])
                    score[i] += n - rank[i][j] + 1
            for (i in score)
                printf "%d\t%s\t%d\n", ++ranking, i, score[i]
        }
    ' day??star?.txt > local_score.txt
}

gen_mod_local_score () {
    awk '
        BEGIN {
            FS = "\t"
            PROCINFO["sorted_in"] = "@val_num_desc"
        }
        { rank[$2] = $1 }
        ENDFILE {
            for (i in rank)
                score[i] += FNR - rank[i] + 1
            delete rank
        }
        END {
            for (i in score)
                printf "%d\t%s\t%d\n", ++ranking, i, score[i]
        }
    ' day??star?.txt > mod_local_score.txt
}

gen_html_files () {
    local re='day([0-9]+)star([0-9])'
    local fname
    for fname in day*star*.txt; do
        [[ $fname =~ $re ]]
        day=${BASH_REMATCH[1]}
        star=${BASH_REMATCH[2]}

        {
            print_header "Ranking day ${day#0}, star $star"
            tablify "$fname" 'Time to solve [H:M]' < "$fname"
        } | tidy -iq --tidy-mark no > "${fname%.txt}.html"
    done

    {
        print_header "Local score"
        echo "<p>For each star, winner gets one point per participant, runner-up one less etc.</p>"
        tablify local_score.txt Points < local_score.txt
    } | tidy -iq --tidy-mark no > local_score.html

    {
        print_header "Modified local score"
        echo "<p>For each star, winner gets one point per submission <em>to that star</em>, runner-up one less etc.</p>"
        tablify mod_local_score.txt Points < mod_local_score.txt
    } | tidy -iq --tidy-mark no > mod_local_score.html
}

gen_index () {
    {
        print_header "Advent of Code 2016, IX Stats"

        cat <<EOF
            <h2>Overall rankings</h2>
            <ul>
            <li><p><a href="data/local_score.html">Local score</a></p></li>
            <li><p><a href="data/mod_local_score.html">Modified local score</a></p></li>
            </ul>
            <h2>Rankings per day and star</h2>
            <div>
            <table>
EOF

        local re='day([0-9]+)star([0-9])'
        for fname in day*star*.html; do
            [[ $fname =~ $re ]]
            day=${BASH_REMATCH[1]}
            star=${BASH_REMATCH[2]}

            if (( star == 1 )); then
                echo "<tr>"
                echo "<td>Day ${day#0}</td>"
                echo "<td><a href=\"data/$fname\">Star 1</a></td>"
            elif (( star == 2 )); then
                echo "<td><a href=\"data/$fname\">Star 2</a></td>"
                echo "</tr>"
            fi
        done

        cat <<EOF
            </table>
            </div>
            <ul>
            <li><p>Script to generate all the stats: <a href="data/rankings">rankings</a></p></li>
            <li><p>JSON source data: <a href="data/leaderboard.json">leaderboard.json</a></p></li>
            <li><p>Suggest more stats in the <a href="https://github.com/bewuethr/advent_of_code/issues">issue tracker</a></p></li>
            </ul>
EOF
    } | tidy -iq --tidy-mark no > ../index.html
}


gen_txt_files
gen_local_score
gen_mod_local_score
gen_html_files
gen_index
